<?php
// this is generated by groundlink-control-tower-bot
ini_set('display_errors', '1');
error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT & ~E_USER_NOTICE & ~E_USER_DEPRECATED);
defined('SHOW_DEBUG_BACKTRACE') || define('SHOW_DEBUG_BACKTRACE', true);
defined('CI_DEBUG') || define('CI_DEBUG', 1);
define('GAME_DB_HOST', '{{host_ip}}');
define('GAME_DB_ID', '{{mysql_user}}');
define('GAME_DB_PASSWORD', '{{mysql_password}}');
define('GAME_DB_PORT', '{{mysql_port}}');
define('GAME_DB_DATABASE', '{{db_mydb}}');
define('LOG_DB_HOST', '{{host_ip}}');
define('LOG_DB_ID', '{{mysql_user}}');
define('LOG_DB_PASSWORD', '{{mysql_password}}');
define('LOG_DB_PORT', '{{mysql_port}}');
define('LOG_DB_DATABASE', '{{db_mydb}}');
define('MAIN_DB_HOST', '{{host_ip}}');
define('MAIN_DB_ID', '{{mysql_user}}');
define('MAIN_DB_PASSWORD', '{{mysql_password}}');
define('MAIN_DB_PORT', '{{mysql_port}}');
define('MAIN_DB_DATABASE', '{{db_main}}');