module.exports =
[
    { 
        id: 'noble',
        developer: false,
        project: 'noble',
        label: 'Noble',
        port: 2001,
        admin_port: 3001,
    },
    { 
        id: 'gamble',
        developer: false,
        project: 'gamble',
        label: 'Gamble',
        port: 2002,
        admin_port: 3002,
    },
    { 
        id: 'nova',
        developer: false,
        project: 'nova',
        label: 'Nova',
        port: 2003,
        admin_port: 3003,
    },
    { 
        id: 'betgo',
        developer: false,
        project: 'betgo',
        label: 'Betgo',
        port: 2004,
        admin_port: 3004,
    },
    { 
        id: 'bets',
        developer: false,
        project: 'bets',
        label: 'Bets',
        port: 2005,
        admin_port: 3005,
    },
    { 
        id: 'ddakbet',
        developer: false,
        project: 'ddakbet',
        label: 'Ddakbet',
        port: 2006,
        admin_port: 3006,
    },
    { 
        id: 'casino',
        developer: false,
        project: 'casino',
        label: 'Evo',
        port: 2007,
        admin_port: 3007,
    },
    { 
        id: 'bulls',
        developer: false,
        project: 'bulls',
        label: 'Bulls',
        port: 2008,
        admin_port: 3008,
    },
    { 
        id: 'guillermo',
        developer: true,
        project: 'gamble',
        label: 'Guillermo',
        port: 1001,
        admin_port: 1002,
    },
    { 
        id: 'emil',
        developer: true,
        project: 'gamble',
        label: 'Emil',
        port: 1003,
        admin_port: 1004,
    },
    { 
        id: 'david',
        developer: true,
        project: 'gamble',
        label: 'David',
        port: 1005,
        admin_port: 1006,
    },
    { 
        id: 'franz',
        developer: true,
        project: 'gamble',
        label: 'Franz',
        port: 1007,
        admin_port: 1008,
    },
    { 
        id: 'anthony',
        developer: true,
        project: 'gamble',
        label: 'Anthony',
        port: 1009,
        admin_port: 1010,
    },
    { 
        id: 'robert',
        developer: true,
        project: 'gamble',
        label: 'Robert',
        port: 1011,
        admin_port: 1012,
    },
]