module.exports =
[
    { 
        id: 'noble',
        developer: false,
        project: 'noble',
        label: 'Noble',
        branch: 'noble',
        branch_main: 'noble_main',
        branch_release: 'noble_release',
        front_username: 'nobledev1',
        front_password: 'noble1234a',
        admin_username: 'nobleadmin1',
        admin_password: 'noble1234a',
        server_name: 'NOBLE',
    },
    {
        id: 'nova',
        developer: false,
        project: 'nova',
        label: 'Nova',
        branch: 'nova',
        branch_main: 'nova_main',
        branch_release: 'nova_release',
        front_username: 'novadev1',
        front_password: 'shqk1234a',
        admin_username: 'novaadmin1',
        admin_password: 'shqk1234a',
        server_name: 'NOVA',
    },
    {
        id: 'gamble',
        developer: false,
        project: 'gamble',
        label: 'Gamble',
        branch: 'gamble',
        branch_main: 'gamble_main',
        branch_release: 'gamble_release',
        front_username: 'gmdev1',
        front_password: 'rpaqmf1234a',
        admin_username: 'charlieadmin',
        admin_password: 'jsjy211217',
        server_name: 'GAMBLE',
    },
    {
        id: 'betgo',
        developer: false,
        project: 'betgo',
        label: 'Betgo',
        branch: 'betgo',
        branch_main: 'betgo_main',
        branch_release: 'betgo_release',
        front_username: 'bgdev1',
        front_password: 'qptrh1234a',
        admin_username: 'bgadmin1',
        admin_password: 'qptrh1234a',
        server_name: 'BETGO',
    },
    {
        id: 'ddakbet',
        developer: false,
        project: 'ddakbet',
        label: 'Ddakbet',
        branch: 'soulbet',
        branch_main: 'soul_bet_main',
        branch_release: 'soul_bet_release',
        front_username: 'nobleadmin1',
        front_password: 'noble1234a',
        admin_username: 'nobleadmin1',
        admin_password: 'noble1234a',
        server_name: 'DDAKBET',
    },
    { 
        id: 'bets',
        developer: false,
        project: 'bets',
        label: 'Bets',
        branch: 'main',
        branch_main: 'main',
        branch_release: 'release',
        front_username: 'betsdev1',
        front_password: 'qptcm1234a',
        admin_username: 'betsadmin1',
        admin_password: 'qptcm1234a',
        server_name: 'BETS',
    },
    { 
        id: 'casino',
        developer: false,
        project: 'casino',
        label: 'Evo',
        branch: 'casino',
        branch_main: 'casino_main',
        branch_release: 'casino_release',
        front_username: 'evodev1',
        front_password: 'dpqh1234a',
        admin_username: 'evoadmin1',
        admin_password: 'dpqh1234a',
        server_name: 'CASINO',
    },
    { 
        id: 'bulls',
        developer: false,
        project: 'bulls',
        label: 'Evo',
        branch: 'bulls',
        branch_main: 'bulls_main',
        branch_release: 'bulls_main',
        front_username: 'bulldev1',
        front_password: 'bulls1234a',
        admin_username: 'bulladmin1',
        admin_password: 'bulls1234a',
        server_name: 'Bulls',
    },
]