version: "2"
services:
  nginx-bulls:
    container_name: 'bulls-nginx'
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /www/bulls:/usr/share/nginx/html
    ports:
      - "2008:80"
      - "3008:81"
    links:
      - php-bulls:php

  php-bulls:
    container_name: 'bulls-php'
    build: ./php
    restart: always
    expose:
      - "9000"
    volumes:
      - /www/bulls:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/php.ini